name: mooncake
description: "Mooncake is a Flutter plugin for mnemonic sentence generation."
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.18.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  vibration: ^2.0.1
  t3_crypto_objects:
    git:
      url: git@github.com:T3-InfoSec/t3-crypto-objects-dart.git
      ref: development
      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
dependency_overrides:
  collection: ^1.19.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.t3.mooncake.mooncake
        pluginClass: MooncakePlugin
      ios:
        pluginClass: MooncakePlugin
      linux:
        pluginClass: MooncakePlugin
      macos:      
        pluginClass: MooncakePlugin
      windows:
        pluginClass: MooncakePluginCApi