name: mooncake
description: "Mooncake is a Flutter plugin for Mooncake plugin"
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.18.0"

dependencies:
  flutter:
    sdk: flutter
  vibration: ^2.0.1
  t3_crypto_objects:
    git:
      url: git@github.com:T3-InfoSec/t3-crypto-objects-dart.git
      ref: initialise_objects
  mooncake_plugin:
    path: mooncake_plugin
      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
dependency_overrides:
  collection: ^1.19.0
